# More information at https://docs.kanboard.org/v1/admin/docker/
name: kanboard
services:
  app:
    image: ghcr.io/kanboard/kanboard:latest
    container_name: kanboard
    ports:
     - "5226:80"
    volumes:
     - ./data:/var/www/app/data
     - ./plugins:/var/www/app/plugins
    environment: 
      - PLUGIN_INSTALLER=true
    networks:
      - caddy
    labels:
      caddy: kanboard.betweenzeroand.one
      caddy.reverse_proxy: "{{upstreams 80}}"
    restart: unless-stopped

volumes:
  data:
    driver: local
  plugins:
    driver: local
  certs:
    driver: local

networks:
  caddy:
    external: true
