services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    environment:
      BIND: ":8923"
      TARGET: "http://b01-zola:80"
      DIFFICULTY: "4"
      #METRICS_BIND: ":9090"
      #SERVE_ROBOTS_TXT: "true"
      #POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      #    ports:
      #      - "8923:8923"
    networks:
      - caddy
    restart: unless-stopped

  zola:
    image: ghcr.io/grfwings/b01-zola:latest
    container_name: b01-zola
    ports:
      - "8180:80"
    networks:
      - caddy
    labels:
      caddy: www.betweenzeroand.one
      caddy.reverse_proxy: http://anubis:8923
      caddy.reverse_proxy.header_up_1: "X-Real-Ip {remote_host}"
      caddy.reverse_proxy.header_up_2: "X-Http_Version {http.request.proto}"
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
