---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=jellyfin.betweenzeroand.one
      - PUID=${USER_ID} 
      - PGID=${GROUP_ID} 
      - TZ=${TIMEZONE}
    network_mode: 'host'
    volumes:
      - jellyfin-config:/config 
      - jellyfin-cache:/cache 
      - type: bind
        source: /srv/jellyfin/media
        target: /media
        read_only: true
    restart: unless-stopped
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID} 
      - TZ=${TIMEZONE}
    volumes: 
      - lidarr-config:/config
      - type: bind
        source: /srv/jellyfin/media/
        target: /jellyfin
      - type: bind
        source: /srv/jellyfin/torrents/
        target: /torrents
    ports:
      - 8686:8686
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID} 
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - type: bind
        source: /srv/jellyfin/torrents/
        target: /torrents
      - qbittorrent-config:/config
    network_mode: service:gluetun
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - gluetn-config:/config
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID} 
      - TZ=${TIMEZONE}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=36PiaVkUwRP4KQI6
      - OPENVPN_PASSWORD=MjMG0ZLdZLJnt0RP3DDmauBhMIaCeKyr
      - UPDATER_PERIOD=24h
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID} 
      - TZ=${TIMEZONE}
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

volumes: 
  jellyfin-config:
  jellyfin-cache:
  lidarr-config:
  qbittorrent-config:
  qbittorrent-downloads:
  gluetn-config:
  prowlarr-config:
